/**
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// NOTE: Ported from Google Cloud GenAI/Imagen to Cloudflare Workers
// - Removed Genkit dependency in favor of Cloudflare-native interfaces
// - Replaced Google AI API calls with generic image generation interface
// - Using Cloudflare R2 for storing generated images
// - Using Cloudflare D1 for tracking generation metadata
// - Using Cloudflare Queues for async image processing

export interface Env {
  // R2 bucket for storing generated images
  IMAGES_BUCKET: R2Bucket;
  
  // D1 database for tracking generation metadata
  DB: D1Database;
  
  // KV namespace for caching model configurations
  MODEL_CACHE: KVNamespace;
  
  // Queue for async image processing
  IMAGE_QUEUE: Queue;
  
  // API keys for image generation services (stored as secrets)
  IMAGE_API_KEY?: string;
  
  // Optional: Cloudflare Access JWT verification
  // JWT_SECRET?: string;
}

/**
 * Image generation configuration schema
 */
export interface ImagenConfig {
  /** Override the API key provided at plugin initialization */
  apiKey?: string;
  
  /** The number of images to generate, from 1 to 4 (inclusive). Default is 1 */
  numberOfImages?: number;
  
  /** Desired aspect ratio of the output image */
  aspectRatio?: '1:1' | '9:16' | '16:9' | '3:4' | '4:3';
  
  /** Control if/how images of people will be generated by the model */
  personGeneration?: 'dont_allow' | 'allow_adult' | 'allow_all';
  
  /** Image generation service to use */
  service?: 'stability' | 'openai' | 'anthropic' | 'custom';
  
  /** Model name/version for the selected service */
  model?: string;
  
  /** Quality setting (service-specific) */
  quality?: 'standard' | 'hd';
  
  /** Style guidance (service-specific) */
  style?: 'natural' | 'vivid' | string;
  
  /** Seed for reproducible results */
  seed?: number;
}

/**
 * Media part containing generated image
 */
export interface MediaPart {
  media: {
    /** URL to the generated image (R2 public URL or data URL) */
    url: string;
    /** MIME type of the image */
    contentType: string;
    /** Optional: R2 object key if stored in bucket */
    objectKey?: string;
    /** Optional: Generation ID for tracking */
    generationId?: string;
  };
}

/**
 * Image generation request
 */
export interface GenerateRequest {
  /** Text prompt for image generation */
  prompt: string;
  
  /** Optional base image for variations/edits (base64 encoded) */
  baseImage?: string;
  
  /** Optional mask image for inpainting (base64 encoded) */
  maskImage?: string;
  
  /** Configuration options */
  config?: ImagenConfig;
  
  /** Optional user ID for tracking/rate limiting */
  userId?: string;
  
  /** Optional request metadata */
  metadata?: Record<string, any>;
}

/**
 * Image generation response
 */
export interface GenerateResponse {
  /** Generated images */
  images: MediaPart[];
  
  /** Generation ID for tracking */
  generationId: string;
  
  /** Processing time in milliseconds */
  processingTime: number;
  
  /** Model/service used */
  model: string;
  
  /** Service used for generation */
  service: string;
  
  /** Optional usage/cost information */
  usage?: {
    /** Number of images generated */
    imageCount: number;
    /** Credits/tokens used */
    credits?: number;
    /** Estimated cost */
    cost?: number;
  };
  
  /** Optional error information */
  error?: {
    code: string;
    message: string;
    details?: any;
  };
}

/**
 * Image generation service interface
 */
export interface ImageGenerationService {
  /** Service name */
  name: string;
  
  /** Generate images from prompt */
  generate(
    request: GenerateRequest,
    env: Env,
    ctx: ExecutionContext
  ): Promise<GenerateResponse>;
  
  /** Check if service is available/configured */
  isAvailable(env: Env): boolean;
}

/**
 * Stability AI image generation service
 */
export class StabilityAIService implements ImageGenerationService {
  name = 'stability';
  
  isAvailable(env: Env): boolean {
    return !!env.IMAGE_API_KEY;
  }
  
  async generate(
    request: GenerateRequest,
    env: Env,
    ctx: ExecutionContext
  ): Promise<GenerateResponse> {
    const apiKey = request.config?.apiKey || env.IMAGE_API_KEY;
    if (!apiKey) {
      throw new Error('Stability AI API key not configured');
    }
    
    const startTime = Date.now();
    const generationId = crypto.randomUUID();
    
    // Prepare request for Stability AI API
    const stabilityRequest = {
      text_prompts: [{ text: request.prompt }],
      cfg_scale: 7,
      height: this.getHeight(request.config?.aspectRatio),
      width: this.getWidth(request.config?.aspectRatio),
      samples: request.config?.numberOfImages || 1,
      steps: 30,
      style_preset: request.config?.style || 'enhance',
    };
    
    // Make API call
    const response = await fetch('https://api.stability.ai/v1/generation/stable-diffusion-xl-1024-v1-0/text-to-image', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
        'Accept': 'application/json',
      },
      body: JSON.stringify(stabilityRequest),
    });
    
    if (!response.ok) {
      const error = await response.text();
      throw new Error(`Stability AI API error: ${response.status} ${error}`);
    }
    
    const result = await response.json();
    
    // Store images in R2 and create media parts
    const images: MediaPart[] = [];
    
    for (const artifact of result.artifacts) {
      const objectKey = `generations/${generationId}/${crypto.randomUUID()}.png`;
      
      // Store in R2
      await env.IMAGES_BUCKET.put(objectKey, this.base64ToArrayBuffer(artifact.base64), {
        httpMetadata: {
          contentType: 'image/png',
        },
        customMetadata: {
          prompt: request.prompt.substring(0, 100),
          userId: request.userId || 'anonymous',
          generationId,
          service: this.name,
          model: request.config?.model || 'stable-diffusion-xl-1024-v1-0',
        },
      });
      
      // Create public URL (or signed URL for private buckets)
      const publicUrl = `/images/${objectKey}`;
      
      images.push({
        media: {
          url: publicUrl,
          contentType: 'image/png',
          objectKey,
          generationId,
        },
      });
    }
    
    // Store generation metadata in D1
    await this.storeGenerationMetadata(request, generationId, images, env, startTime);
    
    return {
      images,
      generationId,
      processingTime: Date.now() - startTime,
      model: request.config?.model || 'stable-diffusion-xl-1024-v1-0',
      service: this.name,
      usage: {
        imageCount: images.length,
      },
    };
  }
  
  private getHeight(aspectRatio?: string): number {
    switch (aspectRatio) {
      case '9:16': return 1024;
      case '16:9': return 576;
      case '3:4': return 896;
      case '4:3': return 768;
      case '1:1':
      default: return 1024;
    }
  }
  
  private getWidth(aspectRatio?: string): number {
    switch (aspectRatio) {
      case '9:16': return 576;
      case '16:9': return 1024;
      case '3:4': return 768;
      case '4:3': return 896;
      case '1:1':
      default: return 1024;
    }
  }
  
  private base64ToArrayBuffer(base64: string): ArrayBuffer {
    const binaryString = atob(base64);
    const bytes = new Uint8Array(binaryString.length);
    for (let i = 0; i < binaryString.length; i++) {
      bytes[i] = binaryString.charCodeAt(i);
    }
    return bytes.buffer;
  }
  
  private async storeGenerationMetadata(
    request: GenerateRequest,
    generationId: string,
    images: MediaPart[],
    env: Env,
    startTime: number
  ): Promise<void> {
    await env.DB.prepare(`
      INSERT INTO image_generations (
        id, user_id, prompt, service, model, 
        aspect_ratio, image_count, processing_time,
        created_at, metadata
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `).bind(
      generationId,
      request.userId || 'anonymous',
      request.prompt,
      this.name,
      request.config?.model || 'stable-diffusion-xl-1024-v1-0',
      request.config?.aspectRatio || '1:1',
      images.length,
      Date.now() - startTime,
      Date.now(),
      JSON.stringify({
        config: request.config,
        metadata: request.metadata,
        image_keys: images.map(img => img.media.objectKey),
      })
    ).run();
  }
}

/**
 * OpenAI DALL-E image generation service
 */
export class OpenAIService implements ImageGenerationService {
  name = 'openai';
  
  isAvailable(env: Env): boolean {
    return !!env.IMAGE_API_KEY;
  }
  
  async generate(
    request: GenerateRequest,
    env: Env,
    ctx: ExecutionContext
  ): Promise<GenerateResponse> {
    // Implementation similar to StabilityAIService but for OpenAI DALL-E
    // NOTE: Simplified for example purposes
    throw new Error('OpenAI DALL-E service not implemented in this example');
  }
}

/**
 * Main image generation service registry
 */
export class ImageGenerationServiceRegistry {
  private services: Map<string, ImageGenerationService> = new Map();
  
  constructor() {
    this.register(new StabilityAIService());
    this.register(new OpenAIService());
  }
  
  register(service: ImageGenerationService): void {
    this.services.set(service.name, service);
  }
  
  getService(name: string): ImageGenerationService | undefined {
    return this.services.get(name);
  }
  
  getAvailableServices(env: Env): string[] {
    return Array.from(this.services.values())
      .filter(service => service.isAvailable(env))
      .map(service => service.name);
  }
  
  getDefaultService(env: Env): string {
    const available = this.getAvailableServices(env);
    return available[0] || 'stability';
  }
}

/**
 * Image generation model reference
 */
export class ImageGenerationModel {
  constructor(
    public name: string,
    public service: string,
    public config: ImagenConfig = {}
  ) {}
  
  /**
   * Generate images using this model
   */
  async generate(
    request: GenerateRequest,
    env: Env,
    ctx: ExecutionContext
  ): Promise<GenerateResponse> {
    const registry = new ImageGenerationServiceRegistry();
    const service = registry.getService(this.service);
    
    if (!service) {
      throw new Error(`Image generation service '${this.service}' not found`);
    }
    
    if (!service.isAvailable(env)) {
      throw new Error(`Image generation service '${this.service}' not available`);
    }
    
    // Merge model config with request config
    const mergedConfig: ImagenConfig = {
      ...this.config,
      ...request.config,
      service: this.service,
      model: this.name,
    };
    
    const requestWithConfig: GenerateRequest = {
      ...request,
      config: mergedConfig,
    };
    
    return service.generate(requestWithConfig, env, ctx);
  }
}

/**
 * Pre-defined image generation models
 */
export const IMAGE_MODELS = {
  'stability/sd-xl': new ImageGenerationModel(
    'stable-diffusion-xl-1024-v1-0',
    'stability',
    {
      aspectRatio: '1:1',
      numberOfImages: 1,
      quality: 'standard',
      style: 'enhance',
    }
  ),
  'stability/sd-xl-hd': new ImageGenerationModel(
    'stable-diffusion-xl-1024-v1-0',
    'stability',
    {
      aspectRatio: '1:1',
      numberOfImages: 1,
      quality: 'hd',
      style: 'photographic',
    }
  ),
  'openai/dall-e-3': new ImageGenerationModel(
    'dall-e-3',
    'openai',
    {
      aspectRatio: '1:1',
      numberOfImages: 1,
      quality: 'standard',
      style: 'vivid',
    }
  ),
};

/**
 * Get an image generation model by name
 */
export function getModel(name: string): ImageGenerationModel {
  const model = IMAGE_MODELS[name as keyof typeof IMAGE_MODELS];
  if (!model) {
    throw new Error(`Image generation model '${name}' not found`);
  }
  return model;
}

/**
 * List available image generation models
 */
export function listModels(env: Env): string[] {
  const registry = new ImageGenerationServiceRegistry();
  const availableServices = registry.getAvailableServices(env);
  
  return Object.keys(IMAGE_MODELS).filter(modelName => {
    const model = IMAGE_MODELS[modelName as keyof typeof IMAGE_MODELS];
    return availableServices.includes(model.service);
  });
}

/**
 * Cloudflare Worker handler for image generation
 */
export async function handleImageGeneration(
  request: Request,
  env: Env,
  ctx: ExecutionContext
): Promise<Response> {
  try {
    // Parse request
    const body = await request.json() as GenerateRequest;
    
    // Validate request
    if (!body.prompt || typeof body.prompt !== 'string') {
      return new Response(
        JSON.stringify({ error: 'Prompt is required and must be a string' }),
        { status: 400, headers: { 'Content-Type': 'application/json' } }
      );
    }
    
    // Get model (default to first available)
    const modelName = body.config?.model || listModels(env)[0];
    if (!modelName) {
      return new Response(
        JSON.stringify({ error: 'No image generation models available' }),
        { status: 503, headers: { 'Content-Type': 'application/json' } }
      );
    }
    
    const model = getModel(modelName);
    
    // Generate images
    const response = await model.generate(body, env, ctx);
    
    return new Response(
      JSON.stringify(response),
      { 
        status: 200, 
        headers: { 
          'Content-Type': 'application/json',
          'Cache-Control': 'no-store',
        } 
      }
    );
    
  } catch (error) {
    console.error('Image generation error:', error);
    
    return new Response(
      JSON.stringify({ 
        error: 'Image generation failed',
        details: error instanceof Error ? error.message : 'Unknown error'
      }),
      { 
        status: 500, 
        headers: { 'Content-Type': 'application/json' } 
      }
    );
  }
}

/**
 * Async image generation via Cloudflare Queue
 */
export async function handleAsyncImageGeneration(
  request: Request,
  env: Env,
  ctx: ExecutionContext
): Promise<Response> {
  try {
    const body = await request.json() as GenerateRequest;
    
    // Validate request
    if (!body.prompt || typeof body.prompt !== 'string') {
      return new Response(
        JSON.stringify({ error: 'Prompt is required and must be a string' }),
        { status: 400, headers: { 'Content-Type': 'application/json' } }
      );
    }
    
    // Generate job ID
    const jobId = crypto.randomUUID();
    
    // Send to queue for async processing
    await env.IMAGE_QUEUE.send({
      jobId,
      ...body,
      timestamp: Date.now(),
    });
    
    return new Response(
      JSON.stringify({
        jobId,
        status: 'queued',
        message: 'Image generation job submitted for async processing',
        checkStatusUrl: `/jobs/${jobId}`,
      }),
      { 
        status: 202, 
        headers: { 'Content-Type': 'application/json' } 
      }
    );
    
  } catch (error) {
    console.error('Async image generation error:', error);
    
    return new Response(
      JSON.stringify({ 
        error: 'Failed to submit image generation job',
        details: error instanceof Error ? error.message : 'Unknown error'
      }),
      { 
        status: 500, 
        headers: { 'Content-Type': 'application/json' } 
      }
    );
  }
}

/**
 * Queue consumer for async image generation
 */
export async function handleImageGenerationQueue(
  batch: MessageBatch<any>,
  env: Env,
  ctx: ExecutionContext
): Promise<void> {
  for (const message of batch.messages) {
    try {
      const job = message.body as GenerateRequest & { jobId: string };
      
      // Get model
      const modelName = job.config?.model || listModels(env)[0];
      if (!modelName) {
        throw new Error('No image generation models available');
      }
      
      const model = getModel(modelName);
      
      // Generate images
      const response = await model.generate(job, env, ctx);
      
      // Store result in KV for retrieval
      await env.MODEL_CACHE.put(
        `job:${job.jobId}`,
        JSON.stringify({
          status: 'completed',
          result: response,
          completedAt: Date.now(),
        }),
        { expirationTtl: 86400 } // 24 hours
      );
      
      message.ack();
      
    } catch (error) {
      console.error('Queue processing error:', error);
      
      // Store error in KV
      const job = message.body as GenerateRequest & { jobId: string };
      await env.MODEL_CACHE.put(
        `job:${job.jobId}`,
        JSON.stringify({
          status: 'failed',
          error: error instanceof Error ? error.message : 'Unknown error',
          failedAt: Date.now(),
        }),
        { expirationTtl: 86400 }
      );
      
      message.retry();
    }
  }
}

/**
 * Check job status
 */
export async function handleJobStatus(
  request: Request,
  env: Env,
  ctx: ExecutionContext
): Promise<Response> {
  const url = new URL(request.url);
  const jobId = url.pathname.split('/').pop();
  
  if (!jobId) {
    return new Response(
      JSON.stringify({ error: 'Job ID is required' }),
      { status: 400, headers: { 'Content-Type': 'application/json' } }
    );
  }
  
  const jobData = await env.MODEL_CACHE.get(`job:${jobId}`);
  
  if (!jobData) {
    return new Response(
      JSON.stringify({ 
        jobId,
        status: 'not_found',
        message: 'Job not found or expired'
      }),
      { status: 404, headers: { 'Content-Type': 'application/json' } }
    );
  }
  
  return new Response(
    jobData,
    { 
      status: 200, 
      headers: { 'Content-Type': 'application/json' } 
    }
  );
}

// Export types and utilities
export type {
  ImagenConfig as ImageGenerationConfig,
  GenerateRequest as ImageGenerationRequest,
  GenerateResponse as ImageGenerationResponse,
};

export const TEST_ONLY = {
  ImageGenerationServiceRegistry,
  StabilityAIService,
  OpenAIService,
  IMAGE_MODELS,
};